# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convaqCpp <- function(df1, df2, model_num, qvalues, qvalues_rep, nthreads, cutoff, comp1, value1, eq1, type1, comp2, value2, eq2, type2) {
    .Call('_rconvaq_convaqCpp', PACKAGE = 'rconvaq', df1, df2, model_num, qvalues, qvalues_rep, nthreads, cutoff, comp1, value1, eq1, type1, comp2, value2, eq2, type2)
}

