# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convaqCpp <- function(df1, df2, model_num, cutoff, qvalues, qvalues_rep, nthreads) {
    .Call('_rconvaq_convaqCpp', PACKAGE = 'rconvaq', df1, df2, model_num, cutoff, qvalues, qvalues_rep, nthreads)
}

